/** @type {import("prettier").Config} */
export default {
	singleQuote: true,
	semi: true,
	tabWidth: 4,
	printWidth: 150,
	useTabs: true,
	quoteProps: 'as-needed',
	trailingComma: 'all',
	bracketSpacing: false,
	bracketSameLine: true,
	plugins: ['prettier-plugin-organize-attributes', 'prettier-plugin-tailwindcss'],
	attributeGroups: [
		'^v-if',
		'^v-else-if',
		'^v-else',
		'^v-model',
		'^v-',
		'^ref',
		'^id',
		'^title',
		'^:title',
		'^:((?!class).)',
		'^class',
		'^:class',
		'^@',
		'$DEFAULT',
	],
	attributeSort: 'ASC',
};
